/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mantenimiento.vista;

import inicio.controlador.clsVentas;
import java.io.File;
import mantenimiento.modelo.daoVentas;

/**
 *
 * @author Edwin
 */
public class frmProcesoVentasdetalle extends javax.swing.JFrame {

    private Object ventasDAO;
 

    /**
     * Creates new form frmProcesoVentasdetalle
     */
    public frmProcesoVentasdetalle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtbuscado = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        txtCuentRef = new javax.swing.JTextField();
        txtCuentSal = new javax.swing.JTextField();
        label9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CbxConcepto = new javax.swing.JComboBox<>();
        label10 = new javax.swing.JLabel();
        txtCuentVal = new javax.swing.JTextField();
        label7 = new javax.swing.JLabel();
        CbxProveedor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 90, 40));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 90, 40));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 90, 40));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 90, 40));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 102));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("?");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 40, 30));

        txtbuscado.setBackground(new java.awt.Color(204, 255, 255));
        txtbuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtbuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 480, 230, 30));

        btnBuscar1.setText("Buscar");
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 100, 40));

        label3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label3.setText("Codigo cuenta a buscar:");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 160, 20));

        label5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label5.setText("Precio de venta");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 40));

        txtCuentRef.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentRef.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentRefActionPerformed(evt);
            }
        });
        getContentPane().add(txtCuentRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 20));

        txtCuentSal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentSal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentSalActionPerformed(evt);
            }
        });
        getContentPane().add(txtCuentSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 20));

        label9.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label9.setText("Saldo de cuenta");
        getContentPane().add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("ID de Concepto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 30));

        CbxConcepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxConceptoActionPerformed(evt);
            }
        });
        getContentPane().add(CbxConcepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 180, 30));

        label10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label10.setText("Valor de la cuenta");
        getContentPane().add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 160, 30));

        txtCuentVal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCuentVal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        txtCuentVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentValActionPerformed(evt);
            }
        });
        getContentPane().add(txtCuentVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 140, 20));

        label7.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        label7.setText("ID de proveedor");
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 30));

        CbxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(CbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, 30));

        tablaVendedores.setBackground(new java.awt.Color(204, 255, 255));
        tablaVendedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaVendedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Vendedor", "ID Empleado", "Correo", "Telefono", "Direccion", "Porcentaje", "Comision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 670, 480));

        jButton2.setText("Ayuda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        daoVentas ventasDAO = new daoVentas();
        clsVentas cuentasporpagarAEliminar = new clsVentas();
        cuentasporpagarAEliminar.setCodproducto(Integer.parseInt(txtbuscado.getText()));
        ventasDAO.delete(cuentasporpagarAEliminar);
        llenadoDeTablas();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed

    
        txtCuentSal.setText("");
        txtCuentVal.setText("");
        txtCuentRef.setText("");
        btnRegistrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        //        // TODO add your handling code here:
        daoVentas ventasDAO = new daoVentas();
        clsVentas cuentasporpagarAActualizar = new clsVentas();
        cuentasporpagarAActualizar.setCodproducto(Integer.parseInt(txtbuscado.getText()));
        cuentasporpagarAActualizar.setCantidadventa(Integer.parseInt(String.valueOf(CbxConcepto.getSelectedItem())));
        cuentasporpagarAActualizar.setCostoventa(Integer.parseInt(String.valueOf(CbxProveedor.getSelectedItem())));
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
     
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtbuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscadoActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void txtCuentRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentRefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentRefActionPerformed

    private void txtCuentSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentSalActionPerformed

    private void CbxConceptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxConceptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxConceptoActionPerformed

    private void txtCuentValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentValActionPerformed

    private void CbxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxProveedorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            if ((new File("src\\main\\java\\ayudas\\ProcesoMayor.chm")).exists()) {
                Process p = Runtime
                .getRuntime()
                .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\ayudas\\ProcesoMayor.chm");
                p.waitFor();
            } else {
                System.out.println("La ayuda no Fue encontrada");
            }
            System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProcesoVentasdetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProcesoVentasdetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProcesoVentasdetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProcesoVentasdetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProcesoVentasdetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxConcepto;
    private javax.swing.JComboBox<String> CbxProveedor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label9;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtCuentRef;
    private javax.swing.JTextField txtCuentSal;
    private javax.swing.JTextField txtCuentVal;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables

    private void llenadoDeTablas() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
